# Generated by Django 4.2.1 on 2023-05-09 13:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=250)),
                ('nazwisko', models.CharField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Pracownik',
            },
        ),
        migrations.CreateModel(
            name='Zwierze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=250, unique=True)),
                ('typ', models.CharField(choices=[('Pies', 'pies'), ('Kot', 'kot')], default='Pies', max_length=4)),
                ('rasa', models.CharField(max_length=250)),
                ('szacowany_wiek', models.IntegerField(validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(1)])),
                ('numer_ewidencyjny', models.IntegerField(unique=True)),
                ('adoptowane', models.BooleanField(default=False)),
                ('kojec', models.BooleanField(default=False)),
                ('pracownik', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pracownik_zwierze', to='schronisko.pracownik')),
            ],
            options={
                'db_table': 'Zwierze',
            },
        ),
        migrations.CreateModel(
            name='Weterynarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=250)),
                ('nazwisko', models.CharField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Weterynarz',
            },
        ),
        migrations.CreateModel(
            name='Kwarantanna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Odbywana', 'odbywana'), ('Nieodbywana', 'nieodbywana')], default='Nieodbywana', max_length=11)),
                ('miejsce', models.IntegerField(default=None, null=True, unique=True)),
                ('data_rozpoczecia', models.DateTimeField(auto_now_add=True)),
                ('weterynarz', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='weterynarz_kwarantanna', to='schronisko.weterynarz')),
                ('zwierze', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zwierze_kwarantanna', to='schronisko.zwierze')),
            ],
            options={
                'db_table': 'Kwarantanna',
            },
        ),
        migrations.CreateModel(
            name='Kojec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('Pies', 'pies'), ('Kot', 'kot')], default='Pies', max_length=4)),
                ('status', models.CharField(choices=[('Zajęte', 'zajęte'), ('Wolne', 'wolne')], default='Wolne', max_length=6)),
                ('numer', models.IntegerField()),
                ('pracownik', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pracownik_kojec', to='schronisko.pracownik')),
                ('zwierze', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='zwierze_kojec', to='schronisko.zwierze')),
            ],
            options={
                'db_table': 'Kojec',
            },
        ),
        migrations.CreateModel(
            name='Kierownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=250)),
                ('nazwisko', models.CharField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Kierownik',
            },
        ),
        migrations.CreateModel(
            name='KartaZdrowia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szczepionka', models.CharField(max_length=250)),
                ('data_szczepienia', models.DateField()),
                ('data_nastepnego_szczepienia', models.DateField()),
                ('weterynarz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='weterynarz_karta_zdrowia', to='schronisko.weterynarz')),
                ('zwierze', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zwierze_karta_zdrowia', to='schronisko.zwierze')),
            ],
            options={
                'db_table': 'KartaZdrowia',
            },
        ),
        migrations.CreateModel(
            name='Badanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj_badania', models.CharField(max_length=250)),
                ('data_badania', models.DateField()),
                ('weterynarz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='weterynarz_badanie', to='schronisko.weterynarz')),
                ('zwierze', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zwierze_badanie', to='schronisko.zwierze')),
            ],
            options={
                'db_table': 'Badanie',
            },
        ),
        migrations.CreateModel(
            name='Adopcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_adoptujacego', models.CharField(max_length=250)),
                ('nazwisko_adoptujacego', models.CharField(max_length=250)),
                ('email_adoptujacego', models.EmailField(max_length=254, unique=True)),
                ('numer_telefonu_adoptujacego', models.IntegerField(unique=True)),
                ('data_adopcji', models.DateTimeField(default=django.utils.timezone.now)),
                ('pracownik', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pracownik_adopcja', to='schronisko.pracownik')),
                ('zwierze', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zwierze_adopcja', to='schronisko.zwierze')),
            ],
            options={
                'db_table': 'Adopcja',
            },
        ),
    ]
